### PR TITLE
Add python 3 support

### PR DESCRIPTION
**Pull request by TuxSH**
Not tested yet

### CODE REVIEW

**Comment by TuxSH** [comment]
image

This gives this weird difference (mostly an off-by-one)... I don't quite understand why

**Comment by nedwill** [comment]
(It's a newline thing as we discussed in IRC when using `'wb'` flags to open the output file.)

**Comment by TuxSH** [comment]
Built with python3, although this gives the same result w/ python2; [soundhax.zip](https://github.com/nedwill/soundhax/files/676326/soundhax.zip)

wb doesn't seem to change anything on python2

**Comment by nedwill** [comment]
Seems to generate a different file, which is bound to happen with a different encoding/decoding process. Let's clear this up once other regions are working.

**Pull request closed without merging**
