### PR TITLE
Partial EUR/JPN support

### PR DESCRIPTION
**Pull request by NexoCube**
clickbait :)

### CODE REVIEW

**Comment by khang06** [comment]
seriously?

**Comment by Sans0Serif** [comment]
Homebrew is not a right.
Do not spam GitHub repos with pointless text. You've done stupid shit like this before, Nexo. Be patient, it is not a fundamental to be able to run homebrew on a kid's toy.

**Comment by NexoCube** [comment]
looks like it is. And @Sans0Serif if u hav a problem, fight me irl m8

**Comment by kade-robertson** [comment]
This is not the point of pull requests, or even the issue tracker.. If you can wait an hour for waithax to run every time you need it you can wait for nedwill to work on this at his own pace. Nobody owes you (or anyone else) anything here.

**Comment by NexoCube** [comment]
That's why i'm "asking"here. there's no other way to speak to nedwill. Github should add a part dedicated to kids like me
And he will probably not answer on twitter

**Comment by Sans0Serif** [comment]
@NexoCube This is just wasting pull space. Don't fill up pull requests will pointless BS, or stupid memes. If you have something to contribute, do it, otherwise sit your $5 ass down before someone makes change. Ned has shit to do, it'll be ready once it's ready.

**Comment by BNTK** [comment]
what a great repo

**Comment by khang06** [comment]
image
this makes it even funnier

**Comment by Jeanolos** [comment]
Ofc. nedwill will implement it 4 u now. He just didn't want to share it early :) (Like the bootrom dump) /s

**Comment by nedwill** [comment]
Blocked user and closed.

**Pull request closed without merging**
